version: "3.8"

services:
  app:
    image: patientor-frontend
    build:
      context: ./patientor-frontend/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    container_name: patientor-frontend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: patientor-reverse-proxy
    depends_on:
      - app
      - server
  server:
    image: patientor-backend
    build: 
      context: ./patientor-backend/
      dockerfile: ./Dockerfile
    ports:
      - 3001:3000
    container_name: patientor-server